### ISSUE TITLE
Deprecated parameter issue

### ISSUE THREAD

**Issue by volodymyrdovhan** [jmbouzan/moodle-mod_ardora#1]
Hello,
I received a deprecated error when tried to save the module:

![image](https://github.com/user-attachments/assets/34661034-806c-4861-9814-f6ffd41d767d)

![image](https://github.com/user-attachments/assets/72279aec-fc72-4bb3-b554-47c224c146a9)

**Comment by jmbouzan** [comment]
Hello.
Deleted second parameter in file_file_icon.
$info->icon = file_file_icon($mainfile);
