### ISSUE TITLE
SQL in implementation

### ISSUE THREAD

**Issue by volodymyrdovhan** [jmbouzan/moodle-mod_ardora#10]
Hello,
please use Moodle DML to implement SQL IN operator or subquery to get IDs and minimise SQL queries.
https://moodledev.io/docs/4.5/apis/core/dml#get_in_or_equal

![image](https://github.com/user-attachments/assets/d8bfc57c-c7dc-43cd-a9f8-1b34411bc0ea)

**Comment by jmbouzan** [comment]
I solved it with "get_in_or_equal":
...
_list($sqlin, $params) = $DB->get_in_or_equal($userids, SQL_PARAMS_NAMED, 'userid');
$params['courseid'] = $courseid;

$sql = "SELECT u.id, u.firstname, u.lastname, g.name as groupname
        FROM {user} u
        INNER JOIN {groups_members} gm ON gm.userid = u.id
        INNER JOIN {groups} g ON g.id = gm.groupid AND g.courseid = :courseid
        WHERE u.id $sqlin";

$users = $DB->get_records_sql($sql, $params);_
...
