### ISSUE TITLE
Passing grade and completion calculation not implemented

### ISSUE THREAD

**Issue by volodymyrdovhan** [jmbouzan/moodle-mod_ardora#11]
Hello,
I didn't find any field which allows to set the Passing Grade for the module:
![image](https://github.com/user-attachments/assets/92256c03-d3bb-4c50-a9b4-6122b926ab85)

In addition, I didn't find the implementation for the Passing grade validation and also module completion calculation in the code.

Please review the plugin and remove not needed completion rules or fully implement module completion processing.

![image](https://github.com/user-attachments/assets/240690bf-e32e-4f65-81d6-ef73f14078db)

**Comment by jmbouzan** [comment]
Corrected. We can now choose ‘passing grade’ if we have specified the minimum passing grade.
