### ISSUE TITLE
Incorrect resourcelib constants names

### ISSUE THREAD

**Issue by volodymyrdovhan** [jmbouzan/moodle-mod_ardora#12]
Hello,

I found incorrect resourcelib constant names in a plugin. Please review and fix the names:

![image](https://github.com/user-attachments/assets/49f9612d-5ce2-452d-98e3-632fdc3c0bff)
![image](https://github.com/user-attachments/assets/dfbb669b-da34-4362-ad3e-52230c17c411)

**Comment by jmbouzan** [comment]
Perfect, thank you.
I have changed ‘RESOURCELIB’ to ‘resourcelib’.
