### ISSUE TITLE
unserialise() function usage

### ISSUE THREAD

**Issue by volodymyrdovhan** [jmbouzan/moodle-mod_ardora#14]
Hello,
please review the logic of serialising and unserialising module displaying options.

![image](https://github.com/user-attachments/assets/4eeaad57-33ed-4229-9701-ac3972814819)

We recognise it as a malicious function and this is a blocker for approval:
https://moodledev.io/general/community/plugincontribution/checklist#security:~:text=%2C%20eval()%2C-,unserialize(),-and%20so%20on

Please consider implementation with json encode/decode.

**Comment by jmbouzan** [comment]
I have changed the use of ‘serialize’ and ‘unserialize’ to ‘json_encode’ and ‘json_decode’.
