### ISSUE TITLE
Global #_SESSION usage

### ISSUE THREAD

**Issue by volodymyrdovhan** [jmbouzan/moodle-mod_ardora#15]
Hello,
I found a global $_SESSION usage in the plugin:
![image](https://github.com/user-attachments/assets/95ef53a6-ef8a-4ecf-927e-4f6a0a993594)

Please consider using session cache as a more secure way or extract the course id from URL parameters.

https://moodledev.io/docs/4.5/apis/subsystems/muc#ad-hoc-caches
https://docs.moodle.org/dev/Cache_API_-_Quick_reference#:~:text=(cache_store%3A%3A-,MODE_SESSION,-%2C%20%27component%27

**Comment by jmbouzan** [comment]
Ok. I have decided to use "session cache".
