### ISSUE TITLE
Privacy API not correctly implemented

### ISSUE THREAD

**Issue by volodymyrdovhan** [jmbouzan/moodle-mod_ardora#2]
Hello,
you implemented Privacy API as null_provider. But your plugin stores personal user information, like userid and other data.

Please implement Privacy API fully with personal user data export and deletion.

![image](https://github.com/user-attachments/assets/2031a5d1-c444-4f30-b66f-62b0b93f7a76)
![image](https://github.com/user-attachments/assets/15305bc3-90d9-4934-9239-ea133f2f7f30)

More documentation:
https://moodledev.io/docs/4.5/apis/subsystems/privacy

You can validate Privacy API implementation with Unit Tests or CLI Utils:
https://moodledev.io/docs/4.5/apis/subsystems/privacy/utils

**Comment by jmbouzan** [comment]
Modified privacy\provider.php file.
