### ISSUE TITLE
Install.xml syntax

### ISSUE THREAD

**Issue by volodymyrdovhan** [jmbouzan/moodle-mod_ardora#3]
Hello,
please review and validate install.xml:
![image](https://github.com/user-attachments/assets/684946a7-766a-411c-885d-e2ba9984c45b)

You can use XMLDB Editor to validate install.xml:
https://moodledev.io/general/development/tools/xmldb

**Comment by jmbouzan** [comment]
Modified and validated install.xml with XMLDB Editor.

**Comment by volodymyrdovhan** [comment]
@jmbouzan One incorrect field definition still exists:
![image](https://github.com/user-attachments/assets/447101b7-2221-4fe2-ae86-cea3539eb99a)
