### ISSUE TITLE
ardora_lib.php usage

### ISSUE THREAD

**Issue by volodymyrdovhan** [jmbouzan/moodle-mod_ardora#4]
Hello,
could you please explain ardora_lib.php file usage? I didn't find how it is using in a plugin.
Is this some endpoint for external calls?

If this file should be used in the plugin - then it should be secured with specific capability validation and sesskey validation.

If this file should be called from outside the system - use External service API to implement it with security token and context/capabilities validation.

![image](https://github.com/user-attachments/assets/c46c83fb-7fd6-4030-b98a-2fdd9d6814f8)

**Comment by jmbouzan** [comment]
Hello.
The file ardora_lib.php is in charge of receiving the AJAX requests from the activities and making/receiving the corresponding function calls. It has been modified to use capability and sesskey validation.

**Comment by volodymyrdovhan** [comment]
@jmbouzan if you want to validate the sesskey - you need to use `require_sesskey()`.
