### ISSUE TITLE
externallib.php in plugin root

### ISSUE THREAD

**Issue by volodymyrdovhan** [jmbouzan/moodle-mod_ardora#5]
Hello,
I didn't find the usage of externallib.php file in a plugin root directory:
![image](https://github.com/user-attachments/assets/2a0c9dc8-abbf-45c5-ae55-ce8fac5e2431)
![image](https://github.com/user-attachments/assets/e2c74d52-695b-4168-8105-1e584fffb3bc)

If it is not used - please delete it.
If you need to use external services from this file - please implement it correctly with External API:
https://moodledev.io/docs/4.1/apis/subsystems/external/writing-a-service

**Comment by jmbouzan** [comment]
Hello.
I deleted it. Thank you.
