### ISSUE TITLE
Hard coded roles IDs

### ISSUE THREAD

**Issue by volodymyrdovhan** [jmbouzan/moodle-mod_ardora#9]
Hello,

it is not a good practice to use hardcoded role IDS to validate permissions:
![image](https://github.com/user-attachments/assets/aa5d2ac6-38d8-4bdd-8634-345487a97d07)

![image](https://github.com/user-attachments/assets/94ea0273-ef4a-41d4-a3cd-1c468d265c08)

![image](https://github.com/user-attachments/assets/e6ba0a3c-9f93-43c3-9400-3e421f3b1a34)

Please use Access API and specific capabilities to validate permissions for the plugin:
https://moodledev.io/docs/4.4/apis/subsystems/access

**Comment by jmbouzan** [comment]
Done. I've corrected it using has_capability()
